import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { CartContextProvider } from "@/contexts/CartContext";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
require("dotenv").config();
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Nike Plus inc. Let's it done",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <CartContextProvider>
      <html lang="en">
        <body>
          <header>
            <Header />
          </header>
          {children}
          <ToastContainer />
          <footer>
            <Footer />
          </footer>
        </body>
      </html>
    </CartContextProvider>
  );
}
